name:        elliptic-curve
version:     0.2.2
synopsis:    Elliptic curve library
description: An extensible library of elliptic curves used in cryptography research
maintainer:  Adjoint Inc (info@adjoint.io)
license:     MIT
github:      adjoint-io/elliptic-curve
category:    Cryptography

default-extensions:
  - LambdaCase
  - RecordWildCards
  - OverloadedStrings
  - NoImplicitPrelude
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - RankNTypes
  - DataKinds
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - MultiParamTypeClasses
  - PatternSynonyms
  - PolyKinds
  - TypeFamilyDependencies

dependencies:
  - base >= 4.10 && < 5
  - protolude
  - galois-field >= 0.4 && < 0.5
  - MonadRandom
  - tasty-quickcheck
  - text
  - wl-pprint-text

extra-source-files:
  - README.md
  - ChangeLog.md

ghc-options:
  - -Wall

library:
  exposed-modules:
    - Curve
    - Curve.Binary
    - Curve.Binary.SECT113R1
    - Curve.Binary.SECT113R2
    - Curve.Binary.SECT131R1
    - Curve.Binary.SECT131R2
    - Curve.Binary.SECT163K1
    - Curve.Binary.SECT163R1
    - Curve.Binary.SECT163R2
    - Curve.Binary.SECT193R1
    - Curve.Binary.SECT193R2
    - Curve.Binary.SECT233K1
    - Curve.Binary.SECT233R1
    - Curve.Binary.SECT239K1
    - Curve.Binary.SECT283K1
    - Curve.Binary.SECT283R1
    - Curve.Binary.SECT409K1
    - Curve.Binary.SECT409R1
    - Curve.Binary.SECT571K1
    - Curve.Binary.SECT571R1
    - Curve.Edwards
    - Curve.Edwards.Curve1174
    - Curve.Edwards.Curve41417
    - Curve.Edwards.E222
    - Curve.Edwards.E382
    - Curve.Edwards.E521
    - Curve.Edwards.Ed448
    - Curve.Edwards.Ed3363
    - Curve.Edwards.Ed25519
    - Curve.Edwards.JubJub
    - Curve.Montgomery
    - Curve.Montgomery.Curve448
    - Curve.Montgomery.Curve25519
    - Curve.Montgomery.Curve383187
    - Curve.Montgomery.M221
    - Curve.Montgomery.M383
    - Curve.Montgomery.M511
    - Curve.Weierstrass
    - Curve.Weierstrass.Anomalous
    - Curve.Weierstrass.ANSSIFRP256V1
    - Curve.Weierstrass.BLS12381
    - Curve.Weierstrass.BLS12381T
    - Curve.Weierstrass.BLS48581
    - Curve.Weierstrass.BLS48581T
    - Curve.Weierstrass.BN224
    - Curve.Weierstrass.BN254
    - Curve.Weierstrass.BN254T
    - Curve.Weierstrass.BN254A
    - Curve.Weierstrass.BN254AT
    - Curve.Weierstrass.BN254B
    - Curve.Weierstrass.BN254BT
    - Curve.Weierstrass.BN256
    - Curve.Weierstrass.BN384
    - Curve.Weierstrass.BN462
    - Curve.Weierstrass.BN462T
    - Curve.Weierstrass.BN512
    - Curve.Weierstrass.SECP112R1
    - Curve.Weierstrass.SECP112R2
    - Curve.Weierstrass.SECP128R1
    - Curve.Weierstrass.SECP128R2
    - Curve.Weierstrass.SECP160K1
    - Curve.Weierstrass.SECP160R1
    - Curve.Weierstrass.SECP160R2
    - Curve.Weierstrass.SECP192K1
    - Curve.Weierstrass.SECP192R1
    - Curve.Weierstrass.SECP224K1
    - Curve.Weierstrass.SECP224R1
    - Curve.Weierstrass.SECP256K1
    - Curve.Weierstrass.SECP256R1
    - Curve.Weierstrass.SECP384R1
    - Curve.Weierstrass.SECP521R1
    - Curve.Weierstrass.BrainpoolP160R1
    - Curve.Weierstrass.BrainpoolP160T1
    - Curve.Weierstrass.BrainpoolP192R1
    - Curve.Weierstrass.BrainpoolP192T1
    - Curve.Weierstrass.BrainpoolP224R1
    - Curve.Weierstrass.BrainpoolP224T1
    - Curve.Weierstrass.BrainpoolP256R1
    - Curve.Weierstrass.BrainpoolP256T1
    - Curve.Weierstrass.BrainpoolP320R1
    - Curve.Weierstrass.BrainpoolP320T1
    - Curve.Weierstrass.BrainpoolP384R1
    - Curve.Weierstrass.BrainpoolP384T1
    - Curve.Weierstrass.BrainpoolP512R1
    - Curve.Weierstrass.BrainpoolP512T1
    - Group
    - Group.Field
    - Group.Field.BN254TF
  other-modules:
    - Generate.Binary.Curve
    - Generate.Binary.Generate
    - Generate.Binary.Parameters
    - Generate.Binary.Types
    - Generate.Curve
    - Generate.Edwards.Curve
    - Generate.Edwards.Generate
    - Generate.Edwards.Parameters
    - Generate.Edwards.Types
    - Generate.Generate
    - Generate.Montgomery.Curve
    - Generate.Montgomery.Generate
    - Generate.Montgomery.Parameters
    - Generate.Montgomery.Types
    - Generate.Pretty
    - Generate.Types
    - Generate.Weierstrass.Curve
    - Generate.Weierstrass.Generate
    - Generate.Weierstrass.Parameters
    - Generate.Weierstrass.Types
    - Main
  source-dirs:
    - src
    - generate

tests:
  elliptic-curve-tests:
    main: Main
    dependencies:
      - arithmoi
      - tasty
      - tasty-hunit
    source-dirs:
      - test
      - src

benchmarks:
  elliptic-curve-benchmarks:
    main: Main
    dependencies:
      - criterion
    source-dirs:
      - bench
      - src
