name:        elliptic-curve
version:     0.3.1
synopsis:    Elliptic curve library
description: An extensible library of elliptic curves used in cryptography research
maintainer:  Adjoint Inc (info@adjoint.io)
license:     MIT
github:      adjoint-io/elliptic-curve
category:    Cryptography

default-extensions:
  - LambdaCase
  - RecordWildCards
  - OverloadedStrings
  - NoImplicitPrelude
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - RankNTypes
  - DataKinds
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - MultiParamTypeClasses
  - OverloadedLists
  - PatternSynonyms
  - PolyKinds
  - TypeFamilyDependencies

dependencies:
  - base >= 4.10 && < 5
  - protolude >= 0.2 && < 0.3
  - galois-field >= 1 && < 2
  - groups
  - MonadRandom
  - tasty-quickcheck
  - text
  - wl-pprint-text

extra-source-files:
  - README.md
  - ChangeLog.md

ghc-options:
  - -freverse-errors
  - -Wall
  - -pgmL markdown-unlit

library:
  exposed-modules:
    - Data.Curve
    - Data.Curve.Binary
    - Data.Curve.Binary.SECT113R1
    - Data.Curve.Binary.SECT113R2
    - Data.Curve.Binary.SECT131R1
    - Data.Curve.Binary.SECT131R2
    - Data.Curve.Binary.SECT163K1
    - Data.Curve.Binary.SECT163R1
    - Data.Curve.Binary.SECT163R2
    - Data.Curve.Binary.SECT193R1
    - Data.Curve.Binary.SECT193R2
    - Data.Curve.Binary.SECT233K1
    - Data.Curve.Binary.SECT233R1
    - Data.Curve.Binary.SECT239K1
    - Data.Curve.Binary.SECT283K1
    - Data.Curve.Binary.SECT283R1
    - Data.Curve.Binary.SECT409K1
    - Data.Curve.Binary.SECT409R1
    - Data.Curve.Binary.SECT571K1
    - Data.Curve.Binary.SECT571R1
    - Data.Curve.Edwards
    - Data.Curve.Edwards.Curve1174
    - Data.Curve.Edwards.Curve41417
    - Data.Curve.Edwards.E222
    - Data.Curve.Edwards.E382
    - Data.Curve.Edwards.E521
    - Data.Curve.Edwards.Ed448
    - Data.Curve.Edwards.Ed3363
    - Data.Curve.Edwards.Ed25519
    - Data.Curve.Edwards.JubJub
    - Data.Curve.Montgomery
    - Data.Curve.Montgomery.Curve448
    - Data.Curve.Montgomery.Curve25519
    - Data.Curve.Montgomery.Curve383187
    - Data.Curve.Montgomery.M221
    - Data.Curve.Montgomery.M383
    - Data.Curve.Montgomery.M511
    - Data.Curve.Weierstrass
    - Data.Curve.Weierstrass.Anomalous
    - Data.Curve.Weierstrass.ANSSIFRP256V1
    - Data.Curve.Weierstrass.BLS12381
    - Data.Curve.Weierstrass.BLS12381T
    - Data.Curve.Weierstrass.BLS48581
    - Data.Curve.Weierstrass.BLS48581T
    - Data.Curve.Weierstrass.BN224
    - Data.Curve.Weierstrass.BN254
    - Data.Curve.Weierstrass.BN254T
    - Data.Curve.Weierstrass.BN254A
    - Data.Curve.Weierstrass.BN254AT
    - Data.Curve.Weierstrass.BN254B
    - Data.Curve.Weierstrass.BN254BT
    - Data.Curve.Weierstrass.BN254C
    - Data.Curve.Weierstrass.BN254CT
    - Data.Curve.Weierstrass.BN254D
    - Data.Curve.Weierstrass.BN254DT
    - Data.Curve.Weierstrass.BN256
    - Data.Curve.Weierstrass.BN384
    - Data.Curve.Weierstrass.BN462
    - Data.Curve.Weierstrass.BN462T
    - Data.Curve.Weierstrass.BN512
    - Data.Curve.Weierstrass.SECP112R1
    - Data.Curve.Weierstrass.SECP112R2
    - Data.Curve.Weierstrass.SECP128R1
    - Data.Curve.Weierstrass.SECP128R2
    - Data.Curve.Weierstrass.SECP160K1
    - Data.Curve.Weierstrass.SECP160R1
    - Data.Curve.Weierstrass.SECP160R2
    - Data.Curve.Weierstrass.SECP192K1
    - Data.Curve.Weierstrass.SECP192R1
    - Data.Curve.Weierstrass.SECP224K1
    - Data.Curve.Weierstrass.SECP224R1
    - Data.Curve.Weierstrass.SECP256K1
    - Data.Curve.Weierstrass.SECP256R1
    - Data.Curve.Weierstrass.SECP384R1
    - Data.Curve.Weierstrass.SECP521R1
    - Data.Curve.Weierstrass.BrainpoolP160R1
    - Data.Curve.Weierstrass.BrainpoolP160T1
    - Data.Curve.Weierstrass.BrainpoolP192R1
    - Data.Curve.Weierstrass.BrainpoolP192T1
    - Data.Curve.Weierstrass.BrainpoolP224R1
    - Data.Curve.Weierstrass.BrainpoolP224T1
    - Data.Curve.Weierstrass.BrainpoolP256R1
    - Data.Curve.Weierstrass.BrainpoolP256T1
    - Data.Curve.Weierstrass.BrainpoolP320R1
    - Data.Curve.Weierstrass.BrainpoolP320T1
    - Data.Curve.Weierstrass.BrainpoolP384R1
    - Data.Curve.Weierstrass.BrainpoolP384T1
    - Data.Curve.Weierstrass.BrainpoolP512R1
    - Data.Curve.Weierstrass.BrainpoolP512T1
  other-modules:
    - Generate.Binary.Curve
    - Generate.Binary.Generate
    - Generate.Binary.Parameters
    - Generate.Binary.Types
    - Generate.Curve
    - Generate.Edwards.Curve
    - Generate.Edwards.Generate
    - Generate.Edwards.Parameters
    - Generate.Edwards.Types
    - Generate.Generate
    - Generate.Montgomery.Curve
    - Generate.Montgomery.Generate
    - Generate.Montgomery.Parameters
    - Generate.Montgomery.Types
    - Generate.Pretty
    - Generate.Types
    - Generate.Weierstrass.Curve
    - Generate.Weierstrass.Generate
    - Generate.Weierstrass.Parameters
    - Generate.Weierstrass.Types
    - Main
  source-dirs:
    - src
    - generate

tests:
  elliptic-curve-tests:
    main: Main
    dependencies:
      - elliptic-curve
      - tasty
      - tasty-hunit
    source-dirs:
      - test

  readme-test:
    dependencies:
      - base
      - protolude
      - elliptic-curve
      - markdown-unlit
    main: README.lhs
    ghc-options: -pgmL markdown-unlit

  example-test:
    dependencies:
      - base
      - protolude
      - elliptic-curve
    main: Example.hs

benchmarks:
  elliptic-curve-benchmarks:
    main: Main
    dependencies:
      - criterion
      - elliptic-curve
    source-dirs:
      - bench
