resolver: lts-13.19
extra-deps:
  - semirings-0.5
  - git: https://github.com/adjoint-io/galois-field.git
    commit: 83b62a3353b1571c20bc84a47c79028880603fdb
  - git: https://github.com/adjoint-io/poly.git
    commit: 1eb5b7a820a685de7c07576e028dee332e3382f8
