resolver: lts-17.3
extra-deps:
  - bitvec-1.0.2.0
  - poly-0.4.0.0
  - semirings-0.5.3
  - mod-0.1.0.0
  - protolude-0.3.0
  - git: https://github.com/serokell/galois-field.git
    commit: 25e564bcd39530dc3139b6ced0dacd81992a0a87
