resolver: lts-13.19
extra-deps:
  - semirings-0.5
  - git: https://github.com/adjoint-io/galois-field.git
    commit: f86b8e881d3b291afd178edb7f673892e8ead54f
  - git: https://github.com/adjoint-io/poly.git
    commit: 1eb5b7a820a685de7c07576e028dee332e3382f8
