name: Cabal CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: cabal-${{ matrix.cabal}} ${{ matrix.ghc }} ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc: [ "9.0.2" "9.2.8" "9.4.5" ]
        cabal: ["3.8", "3.10"]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup stack
      uses: haskell/actions/setup@v2
      with:
        enable-stack: true
        stack-version: 'latest'

    - uses: actions/cache@v3
      name: Cache ~/.cabal/packages
      with:
        path: ~/.cabal/packages
        key: cabal-packages-${{ matrix.ghc }}

    - uses: actions/cache@v3
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: cabal-store-${{ matrix.ghc }}

    - uses: actions/cache@v3
      name: Cache dist-newstyle
      with:
        path: dist-newstyle
        key: dist-newstyle-${{ matrix.ghc }}

    - name: Install dependencies
      run: |
        cabal update
    - name: Build
      run: |
        cabal new-install tasty-discover
        cabal new-build
